package net.exshinigami.remembrance.model;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import net.exshinigami.remembrance.model.User;
import net.exshinigami.remembrance.model.Message;
import net.exshinigami.remembrance.model.Picture;

import net.exshinigami.remembrance.model.UserDao;
import net.exshinigami.remembrance.model.MessageDao;
import net.exshinigami.remembrance.model.PictureDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userDaoConfig;
    private final DaoConfig messageDaoConfig;
    private final DaoConfig pictureDaoConfig;

    private final UserDao userDao;
    private final MessageDao messageDao;
    private final PictureDao pictureDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        messageDaoConfig = daoConfigMap.get(MessageDao.class).clone();
        messageDaoConfig.initIdentityScope(type);

        pictureDaoConfig = daoConfigMap.get(PictureDao.class).clone();
        pictureDaoConfig.initIdentityScope(type);

        userDao = new UserDao(userDaoConfig, this);
        messageDao = new MessageDao(messageDaoConfig, this);
        pictureDao = new PictureDao(pictureDaoConfig, this);

        registerDao(User.class, userDao);
        registerDao(Message.class, messageDao);
        registerDao(Picture.class, pictureDao);
    }
    
    public void clear() {
        userDaoConfig.getIdentityScope().clear();
        messageDaoConfig.getIdentityScope().clear();
        pictureDaoConfig.getIdentityScope().clear();
    }

    public UserDao getUserDao() {
        return userDao;
    }

    public MessageDao getMessageDao() {
        return messageDao;
    }

    public PictureDao getPictureDao() {
        return pictureDao;
    }

}
