package net.exshinigami.remembrance.model;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import java.util.List;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.query.Query;
import de.greenrobot.dao.query.QueryBuilder;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "MESSAGE".
*/
public class MessageDao extends AbstractDao<Message, Long> {

    public static final String TABLENAME = "MESSAGE";

    /**
     * Properties of entity Message.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Text = new Property(1, String.class, "text", false, "TEXT");
        public final static Property Command = new Property(2, String.class, "command", false, "COMMAND");
        public final static Property Uploaded = new Property(3, boolean.class, "uploaded", false, "UPLOADED");
        public final static Property Created = new Property(4, java.util.Date.class, "created", false, "CREATED");
        public final static Property Updated = new Property(5, java.util.Date.class, "updated", false, "UPDATED");
        public final static Property Enabled = new Property(6, boolean.class, "enabled", false, "ENABLED");
        public final static Property UserId = new Property(7, long.class, "userId", false, "USER_ID");
    };

    private Query<Message> user_MessageListQuery;

    public MessageDao(DaoConfig config) {
        super(config);
    }
    
    public MessageDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"MESSAGE\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"TEXT\" TEXT NOT NULL ," + // 1: text
                "\"COMMAND\" TEXT NOT NULL ," + // 2: command
                "\"UPLOADED\" INTEGER NOT NULL ," + // 3: uploaded
                "\"CREATED\" INTEGER NOT NULL ," + // 4: created
                "\"UPDATED\" INTEGER NOT NULL ," + // 5: updated
                "\"ENABLED\" INTEGER NOT NULL ," + // 6: enabled
                "\"USER_ID\" INTEGER NOT NULL );"); // 7: userId
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"MESSAGE\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Message entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getText());
        stmt.bindString(3, entity.getCommand());
        stmt.bindLong(4, entity.getUploaded() ? 1L: 0L);
        stmt.bindLong(5, entity.getCreated().getTime());
        stmt.bindLong(6, entity.getUpdated().getTime());
        stmt.bindLong(7, entity.getEnabled() ? 1L: 0L);
        stmt.bindLong(8, entity.getUserId());
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public Message readEntity(Cursor cursor, int offset) {
        Message entity = new Message( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getString(offset + 1), // text
            cursor.getString(offset + 2), // command
            cursor.getShort(offset + 3) != 0, // uploaded
            new java.util.Date(cursor.getLong(offset + 4)), // created
            new java.util.Date(cursor.getLong(offset + 5)), // updated
            cursor.getShort(offset + 6) != 0, // enabled
            cursor.getLong(offset + 7) // userId
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Message entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setText(cursor.getString(offset + 1));
        entity.setCommand(cursor.getString(offset + 2));
        entity.setUploaded(cursor.getShort(offset + 3) != 0);
        entity.setCreated(new java.util.Date(cursor.getLong(offset + 4)));
        entity.setUpdated(new java.util.Date(cursor.getLong(offset + 5)));
        entity.setEnabled(cursor.getShort(offset + 6) != 0);
        entity.setUserId(cursor.getLong(offset + 7));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(Message entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(Message entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "messageList" to-many relationship of User. */
    public List<Message> _queryUser_MessageList(long userId) {
        synchronized (this) {
            if (user_MessageListQuery == null) {
                QueryBuilder<Message> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.UserId.eq(null));
                user_MessageListQuery = queryBuilder.build();
            }
        }
        Query<Message> query = user_MessageListQuery.forCurrentThread();
        query.setParameter(0, userId);
        return query.list();
    }

}
