package net.exshinigami.remembrance.model;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
import java.util.Date;

import de.greenrobot.dao.DaoException;
// KEEP INCLUDES END
/**
 * Entity mapped to table "MESSAGE".
 */
public class Message extends BaseEntity  implements Savable {

    private Long id;
    /** Not-null value. */
    private String text;
    /** Not-null value. */
    private String command;
    private boolean uploaded;
    /** Not-null value. */
    private java.util.Date created;
    /** Not-null value. */
    private java.util.Date updated;
    private boolean enabled;
    private long userId;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Message() {
    }

    public Message(Long id) {
        this.id = id;
    }

    public Message(Long id, String text, String command, boolean uploaded, java.util.Date created, java.util.Date updated, boolean enabled, long userId) {
        this.id = id;
        this.text = text;
        this.command = command;
        this.uploaded = uploaded;
        this.created = created;
        this.updated = updated;
        this.enabled = enabled;
        this.userId = userId;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getText() {
        return text;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setText(String text) {
        this.text = text;
    }

    /** Not-null value. */
    public String getCommand() {
        return command;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCommand(String command) {
        this.command = command;
    }

    public boolean getUploaded() {
        return uploaded;
    }

    public void setUploaded(boolean uploaded) {
        this.uploaded = uploaded;
    }

    /** Not-null value. */
    public java.util.Date getCreated() {
        return created;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCreated(java.util.Date created) {
        this.created = created;
    }

    /** Not-null value. */
    public java.util.Date getUpdated() {
        return updated;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUpdated(java.util.Date updated) {
        this.updated = updated;
    }

    public boolean getEnabled() {
        return enabled;
    }

    public void setEnabled(boolean enabled) {
        this.enabled = enabled;
    }

    public long getUserId() {
        return userId;
    }

    public void setUserId(long userId) {
        this.userId = userId;
    }

    // KEEP METHODS - put your custom methods here



    public static Message get(DaoSession daoSession, long id) throws DoesNotExist{
        Message message = daoSession.getMessageDao().load(id);
        synchronized (Message.class) {
            if (message == null) {
                throw new DoesNotExist();
            }
        }
        return message;
    }

    public static Message getOrCreate(DaoSession daoSession, long id, String text, String command, long userId) {
        Message message;
        try {
            message = get(daoSession, id);
        }catch (DaoException|DoesNotExist e) {
            message = create(text, command, userId);
            message.save(daoSession);
        }
        return message;
    }

    public static synchronized Message create(String text, String command, long userId) {
        Message message = new Message();
        message.setDefault();
        message.setText(text);
        message.setCommand(command);
        message.setUserId(userId);
        return message;
    }

    @Override
    public long save(DaoSession daoSession) {
        return daoSession.getMessageDao().insert(this);
    }

    @Override
    protected void setDefault() {
        Date today = new Date();
        setCreated(today);
        setUpdated(today);
        setEnabled(true);
        setUploaded(false);
    }
    // KEEP METHODS END

}
