package net.exshinigami.remembrance.model;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import java.util.List;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.query.Query;
import de.greenrobot.dao.query.QueryBuilder;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "PICTURE".
*/
public class PictureDao extends AbstractDao<Picture, Long> {

    public static final String TABLENAME = "PICTURE";

    /**
     * Properties of entity Picture.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Name = new Property(1, String.class, "name", false, "NAME");
        public final static Property Uploaded = new Property(2, boolean.class, "uploaded", false, "UPLOADED");
        public final static Property Created = new Property(3, java.util.Date.class, "created", false, "CREATED");
        public final static Property Updated = new Property(4, java.util.Date.class, "updated", false, "UPDATED");
        public final static Property Enabled = new Property(5, boolean.class, "enabled", false, "ENABLED");
        public final static Property UserId = new Property(6, long.class, "userId", false, "USER_ID");
    };

    private Query<Picture> user_PictureListQuery;

    public PictureDao(DaoConfig config) {
        super(config);
    }
    
    public PictureDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"PICTURE\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"NAME\" TEXT NOT NULL UNIQUE ," + // 1: name
                "\"UPLOADED\" INTEGER NOT NULL ," + // 2: uploaded
                "\"CREATED\" INTEGER NOT NULL ," + // 3: created
                "\"UPDATED\" INTEGER NOT NULL ," + // 4: updated
                "\"ENABLED\" INTEGER NOT NULL ," + // 5: enabled
                "\"USER_ID\" INTEGER NOT NULL );"); // 6: userId
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"PICTURE\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Picture entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getName());
        stmt.bindLong(3, entity.getUploaded() ? 1L: 0L);
        stmt.bindLong(4, entity.getCreated().getTime());
        stmt.bindLong(5, entity.getUpdated().getTime());
        stmt.bindLong(6, entity.getEnabled() ? 1L: 0L);
        stmt.bindLong(7, entity.getUserId());
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public Picture readEntity(Cursor cursor, int offset) {
        Picture entity = new Picture( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getString(offset + 1), // name
            cursor.getShort(offset + 2) != 0, // uploaded
            new java.util.Date(cursor.getLong(offset + 3)), // created
            new java.util.Date(cursor.getLong(offset + 4)), // updated
            cursor.getShort(offset + 5) != 0, // enabled
            cursor.getLong(offset + 6) // userId
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Picture entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setName(cursor.getString(offset + 1));
        entity.setUploaded(cursor.getShort(offset + 2) != 0);
        entity.setCreated(new java.util.Date(cursor.getLong(offset + 3)));
        entity.setUpdated(new java.util.Date(cursor.getLong(offset + 4)));
        entity.setEnabled(cursor.getShort(offset + 5) != 0);
        entity.setUserId(cursor.getLong(offset + 6));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(Picture entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(Picture entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "pictureList" to-many relationship of User. */
    public List<Picture> _queryUser_PictureList(long userId) {
        synchronized (this) {
            if (user_PictureListQuery == null) {
                QueryBuilder<Picture> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.UserId.eq(null));
                user_PictureListQuery = queryBuilder.build();
            }
        }
        Query<Picture> query = user_PictureListQuery.forCurrentThread();
        query.setParameter(0, userId);
        return query.list();
    }

}
