package net.exshinigami.remembrance.model;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "PICTURE".
 */
public class Picture {

    private Long id;
    private String name;
    private Boolean uploaded;
    private long userId;

    public Picture() {
    }

    public Picture(Long id) {
        this.id = id;
    }

    public Picture(Long id, String name, Boolean uploaded, long userId) {
        this.id = id;
        this.name = name;
        this.uploaded = uploaded;
        this.userId = userId;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Boolean getUploaded() {
        return uploaded;
    }

    public void setUploaded(Boolean uploaded) {
        this.uploaded = uploaded;
    }

    public long getUserId() {
        return userId;
    }

    public void setUserId(long userId) {
        this.userId = userId;
    }

}
