package net.exshinigami.remembrance.model;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "USER".
*/
public class UserDao extends AbstractDao<User, Long> {

    public static final String TABLENAME = "USER";

    /**
     * Properties of entity User.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property MobileNumber = new Property(1, String.class, "mobileNumber", false, "MOBILE_NUMBER");
        public final static Property Type = new Property(2, String.class, "type", false, "TYPE");
        public final static Property SmsCount = new Property(3, long.class, "smsCount", false, "SMS_COUNT");
        public final static Property SpamCount = new Property(4, long.class, "spamCount", false, "SPAM_COUNT");
        public final static Property Created = new Property(5, java.util.Date.class, "created", false, "CREATED");
        public final static Property Updated = new Property(6, java.util.Date.class, "updated", false, "UPDATED");
        public final static Property Enabled = new Property(7, boolean.class, "enabled", false, "ENABLED");
    };

    private DaoSession daoSession;


    public UserDao(DaoConfig config) {
        super(config);
    }
    
    public UserDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"USER\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"MOBILE_NUMBER\" TEXT NOT NULL UNIQUE ," + // 1: mobileNumber
                "\"TYPE\" TEXT NOT NULL ," + // 2: type
                "\"SMS_COUNT\" INTEGER NOT NULL ," + // 3: smsCount
                "\"SPAM_COUNT\" INTEGER NOT NULL ," + // 4: spamCount
                "\"CREATED\" INTEGER NOT NULL ," + // 5: created
                "\"UPDATED\" INTEGER NOT NULL ," + // 6: updated
                "\"ENABLED\" INTEGER NOT NULL );"); // 7: enabled
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"USER\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, User entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getMobileNumber());
        stmt.bindString(3, entity.getType());
        stmt.bindLong(4, entity.getSmsCount());
        stmt.bindLong(5, entity.getSpamCount());
        stmt.bindLong(6, entity.getCreated().getTime());
        stmt.bindLong(7, entity.getUpdated().getTime());
        stmt.bindLong(8, entity.getEnabled() ? 1L: 0L);
    }

    @Override
    protected void attachEntity(User entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public User readEntity(Cursor cursor, int offset) {
        User entity = new User( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getString(offset + 1), // mobileNumber
            cursor.getString(offset + 2), // type
            cursor.getLong(offset + 3), // smsCount
            cursor.getLong(offset + 4), // spamCount
            new java.util.Date(cursor.getLong(offset + 5)), // created
            new java.util.Date(cursor.getLong(offset + 6)), // updated
            cursor.getShort(offset + 7) != 0 // enabled
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, User entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setMobileNumber(cursor.getString(offset + 1));
        entity.setType(cursor.getString(offset + 2));
        entity.setSmsCount(cursor.getLong(offset + 3));
        entity.setSpamCount(cursor.getLong(offset + 4));
        entity.setCreated(new java.util.Date(cursor.getLong(offset + 5)));
        entity.setUpdated(new java.util.Date(cursor.getLong(offset + 6)));
        entity.setEnabled(cursor.getShort(offset + 7) != 0);
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(User entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(User entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
